### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by vpjacob** [rongcloud/rongcloud-react-native-imlib#10]
DATABASE_ERROR = 33002,
这是什么问题

**Comment by qiuxiang** [comment]
什么情况下出现的？

**Comment by vpjacob** [comment]
import { connect as Connect, init } from 'rongcloud-react-native-imlib';
                    init(Constants.CHAT_APP_KEY);
                    Connect(data.token,(e)=>{
                        console.log('success======',e);
                    },(e)=>{
                        console.log('======',e);
                    });
Connect的成功和失败不走。。



在另外界面调用，
import { sendMessage, ConversationType } from "rongcloud-react-native-imlib";
const conversationType = ConversationType.PRIVATE;
const targetId = "28649"; // 根据会话类型的不同，可以是用户 ID、讨论组 ID、组群 ID 等
const content = { type: "text", content: "Hello" };
const callback = {
    success(messageId) {
        console.log("发送成功：" + messageId);
    },
    error(errorCode) {
        console.log("发送失败：" + errorCode);
    }
};

打印出现
发送失败：33002

**Comment by vpjacob** [comment]
```
import { connect as Connect, init } from 'rongcloud-react-native-imlib';

                    init(Constants.CHAT_APP_KEY);
                    Connect(data.token,(e)=>{
                        console.log('success======',e);
                    },(e)=>{
                        console.log('======',e);
                    });

Connect的成功和失败不走。。

在另外界面调用，
import { sendMessage, ConversationType } from "rongcloud-react-native-imlib";


const conversationType = ConversationType.PRIVATE;
const targetId = "28649"; // 28649 是我另外个账号，获取过token
const content = { type: "text", content: "Hello" };
const callback = {
    success(messageId) {
        console.log("发送成功：" + messageId);
    },
    error(errorCode) {
        console.log("发送失败：" + errorCode);
    }
};


打印出现
发送失败：33002



```

**Comment by qiuxiang** [comment]
https://qiuxiang.github.io/react-native-rongcloud-imlib/api/modules/rcimclient.html#connect
connect 还有第三个回调，tokenIncorrect 的回调，很可能是因为 token 不正确。

**Comment by vpjacob** [comment]
追加第三个参数也不可以，接受不到，回调。
connect调用后，必有一个方法走吗？

```
                    IMClient.connect(data.token,(e)=>{
                        console.log('success======',e);
                    },(e)=>{
                        console.log('======e',e);
                    },(e)=>{
                        console.log('======e',e);
                    });


```
请问，不走回调是什么情况
`token: "gtJjgVWkuDpQxeV4dB+htyIVIyAQ0BKQ8xZfbWzIoEbkdgDyVZq0c8eLhz1tOtn+ImcnOrJaq8sS8RiHqfzwHw=="`

**Comment by qiuxiang** [comment]
https://qiuxiang.github.io/react-native-rongcloud-imlib/api/modules/rcimclient.html#addconnectionstatuslistener 这个方法也试试

**Comment by qiuxiang** [comment]
你现在测试的是 ios 还是 android？

**Comment by vpjacob** [comment]
ios 的，我集成，就写了
init 
connect
sendMessage
三个主要方法，

**Comment by vpjacob** [comment]
```
        const listener = IMClient.addConnectionStatusListener(status => console.log('=======chatstatus',status));


```
无反应，写在connect方法之后

**Comment by vpjacob** [comment]
难道是，导入ios包，有问题？桥接文件没有，调用成功，SDK？？？

**Comment by qiuxiang** [comment]
你可以试下运行这个项目的 example app

**Comment by vpjacob** [comment]
我问题是，后台忘记返回code码。

**Comment by Time-coding** [comment]
Rn60.5,init初始化失败，Cannot read property 'init' of undefined
