### ISSUE TITLE
参数名错误

### ISSUE THREAD

**Issue by yunwuxin** [rongcloud/rongcloud-react-native-imlib#11]
https://github.com/rongcloud/rongcloud-react-native-imlib/blob/f3d867c7a31fd63f79ccea943b6863a39bbdcb5e/lib/ios/RCIMClib.m#L1598-L1599

这两个地方的`lastest`都多了个`s`  和安卓的不一致

**Comment by qiuxiang** [comment]
= = 原来 iOS SDK 就拼错了
