### ISSUE TITLE
如何发送一个 跳转 界面的message

### ISSUE THREAD

**Issue by vpjacob** [rongcloud/rongcloud-react-native-imlib#13]
预期：发送一个跳转到RNPage的消息，点击消息后，跳转，
疑问：需要使用哪一种type  （type: 'text'，type: "image";type: "command";）

是CommandMessage吗？
试了试，发送CommandMessage 失败

**Comment by vpjacob** [comment]
还有rn 文档中没有写上推送功能，请问，支持的接口有没有

**Comment by qiuxiang** [comment]
command 还需要另外支持，不过在这之前我打算先优化 messageType 的处理

**Comment by qiuxiang** [comment]
关于推送，你可以看这个示例 https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/example/examples/push-receiver.js ，但只是针对 Android，iOS 推送请参考：https://www.rongcloud.cn/docs/message_and_push_system.html#ios 。

RN 处理离线推送是无力的，因为前台进程退出后，js 端就无论如何也处理不了推送了。这时候推送消息只能于点击后唤醒应用，如果你要对离线推送作出反应，只能是通过原生代码实现。

**Comment by vpjacob** [comment]
融云SDK能实现，离线消息，弹出推送通知和消息内容吗，能自定义键值对吗？

**Comment by qiuxiang** [comment]
这些是支持的

**Comment by vpjacob** [comment]
```

export declare function getHistoryMessages(conversationType: ConversationType, targetId: string, objectNames: MessageObjectName[], timestamp: number, count: number, isForward: boolean): Promise<Message[]>;


1.timestamp 传入 receivedTime还是sendtime

2.
        let messages = await getHistoryMessages(
            ConversationType.PRIVATE,targetId,
            ['text','image','file','location','voice',],
            _.get(messages,[messages.length - 1,'receivedTime']),
           20,
          true
      );
这个方法返回空数组，是 MessageObjectName写的不对吗

```

**Comment by qiuxiang** [comment]
timestamp 一般就是指发送时间；getHistoryMessages 具体参数看接口文档 https://qiuxiang.github.io/react-native-rongcloud-imlib/api/modules/rcimclient.html#gethistorymessages

你这里用的 ObjectName 不对，应该是 https://qiuxiang.github.io/react-native-rongcloud-imlib/api/modules/rcimclient.html#messageobjectname ，当然，这个最好还是提供 enum 来使用，而不用关心具体的值是什么，这也就是我现在正在改进的。

**Comment by qiuxiang** [comment]
Command 的发送已经支持了，用法是：
```javascript
import { sendMessage, ConversationType, ObjectName } from "rongcloud-react-native-imlib";

const conversationType = ConversationType.PRIVATE;
const targetId = "n19jmcy59f1q9";
const content = { objectName: ObjectName.Command, name: "CmdName", data: "CmdData" };

sendMessage( { conversationType, targetId, content });
```

**Comment by vpjacob** [comment]
`getConversationList`
通过这个方法，不能获取到列表的头像吗

**Comment by qiuxiang** [comment]
Conversation 没有头像的数据

**Comment by vpjacob** [comment]
> Command 的发送已经支持了，用法是：
> 
> ```js
> import { sendMessage, ConversationType, ObjectName } from "rongcloud-react-native-imlib";
> 
> const conversationType = ConversationType.PRIVATE;
> const targetId = "n19jmcy59f1q9";
> const content = { objectName: ObjectName.Command, name: "CmdName", data: "CmdData" };
> 
> sendMessage( { conversationType, targetId, content });
> ```

发送倒是可以了，`getConversationList ` 和 `getHistoryMessages`
获取不到，Command 消息

**Comment by qiuxiang** [comment]
命令消息不存储，不能用这些方法获取到，只能在消息监听函数那里及时处理

**Comment by vpjacob** [comment]
```

        sendMessage({
            conversationType: ConversationType.PRIVATE,
            targetId,
            content: {
                objectName: ObjectName.Text,
                content: messages[ 0 ].text,
            },
            pushContent: 'string',
            pushData: 'string',
        });

在你们网站上测试，可以收到Test推送
两部手机，发送离线消息，收不到推送
```

**Comment by vpjacob** [comment]
```
        const messages = await getHistoryMessages(ConversationType.PRIVATE, targetId,[ ObjectName.Text, ObjectName.Command, ObjectName.Image ]);
安卓崩溃

在getHistoryMessagesByTimestamp方法中报错  

toStringArray

[https://github.com/rongcloud/rongcloud-react-native-imlib/blob/a1506dc9b044d568153ad4df829e22092dce041b/lib/android/src/main/java/cn/rongcloud/imlib/react/RCIMClientModule.java](url)

```

**Comment by qiuxiang** [comment]
@vpjacob 不要在一个 issue 讨论太多其他问题，新问题在新 issue 针对讨论，这个 issue 我先关掉了。

另外，报错最好提供截图。
