### ISSUE TITLE
android 9系统连接不上

### ISSUE THREAD

**Issue by bawfv** [rongcloud/rongcloud-react-native-imlib#14]
两部安卓机，android 6系统的没为题，android 9系统连接不上，不走成功回调也不走失败回调，这是什么情况？

**Comment by qiuxiang** [comment]
看下这些 #10 #4

**Comment by bawfv** [comment]
> 看下这些 #10 #4

我把build target降级为23，连接倒是成功了，也能发送接收消息，但是app底部出现大概20像素的黑边

**Comment by bawfv** [comment]
可以了，buildtarge降级为23，就要做全屏适配

**Comment by qiuxiang** [comment]
这个会稍做说明，怎么在 23+ 使用，其实主要是 libsqlite 集成的问题
