### ISSUE TITLE
安卓getHistoryMessages报错

### ISSUE THREAD

**Issue by vpjacob** [rongcloud/rongcloud-react-native-imlib#15]
```
const messages = await getHistoryMessages(ConversationType.PRIVATE, targetId,[ ObjectName.Text, ObjectName.Command, ObjectName.Image ]);
安卓崩溃
```
![541558666263_ pic_hd](https://user-images.githubusercontent.com/22218458/58299493-de433100-7e11-11e9-85a2-4e4b4188322b.jpg)

getConversationList获取不到头像，那么正确做法是，我再请求自己服务器吗？

**Comment by vpjacob** [comment]
@qiuxiang 是我自己的问题还是SDK问题呢？

**Comment by qiuxiang** [comment]
确实是没处理好，已提交修复
