### ISSUE TITLE
启动报错，请帮忙看下什么原因

### ISSUE THREAD

**Issue by linhanyang** [rongcloud/rongcloud-react-native-imlib#16]
<img width="390" alt="WX20190527-204309@2x" src="https://user-images.githubusercontent.com/7603016/58420559-2a1b0200-80c0-11e9-9194-f6037b6c4177.png">

**Comment by linhanyang** [comment]
<img width="1408" alt="WX20190527-204521@2x" src="https://user-images.githubusercontent.com/7603016/58420629-60f11800-80c0-11e9-8d74-fedc12aa2ebf.png">
Xcodek控制台报错信息。

**Comment by qiuxiang** [comment]
这是 react-native 的问题，dev server 没启动，或某种原因启动了，但没有映射成功。先试试 `npm start`，然后重新加载。
