### ISSUE TITLE
'RongIMLib/RongIMLib.h' file not found

### ISSUE THREAD

**Issue by mhpyzzy** [rongcloud/rongcloud-react-native-imlib#2]
运行时报错：'RongIMLib/RongIMLib.h' file not found

**Comment by qiuxiang** [comment]
下载 sdk 放到 ios 目录了吗？

**Comment by mhpyzzy** [comment]
没有，我是用react-native link

**Comment by mhpyzzy** [comment]
另外问一下，什么时候可以支持 多人音视频聊天啊？

**Comment by qiuxiang** [comment]
只是 link 还不行，具体看文档 https://www.rongcloud.cn/docs/react_native_imlib.html

**Comment by chinavane** [comment]
![image](https://user-images.githubusercontent.com/8588836/57188093-89577d80-6f2b-11e9-9b4a-73c622d29032.png)
参见文档配置还是文件找不到。

**Comment by qiuxiang** [comment]
@chinavane 看一下你的 ios 目录
