### ISSUE TITLE
发送消息，一直失败。错误码：-3

### ISSUE THREAD

**Issue by luyixin** [rongcloud/rongcloud-react-native-imlib#20]
发送消息，一直失败。错误码：-3，
链接没问题，发送一直出错，错误码-3，卡了2天了。版本:0.2.1

**Comment by luyixin** [comment]
![image](https://user-images.githubusercontent.com/16029204/59077745-75c67a80-890e-11e9-899d-ceefa93e7827.png)

**Comment by qiuxiang** [comment]
conversationType 首字母不大写

**Comment by luyixin** [comment]
额，我的失误
