### ISSUE TITLE
融云的RN的demo无法运行，安卓编译通过了，但是无法运行！

### ISSUE THREAD

**Issue by cnpmge** [rongcloud/rongcloud-react-native-imlib#22]
我在融云的RN的demo上按照步骤进行操作，但是项目无法正常运行，是什么原因呢？
![QQ截图20190612110928](https://user-images.githubusercontent.com/48587696/59321432-90c92e00-8d04-11e9-985f-6f7e5a336f5d.png)

**Comment by qiuxiang** [comment]
本地环境的问题吧

**Comment by cnpmge** [comment]
> 本地环境的问题吧

运行其它项目没问题的
