### ISSUE TITLE
重大BUG！！！安卓7以上缺少依赖包文件，导致APP闪退

### ISSUE THREAD

**Issue by luyixin** [rongcloud/rongcloud-react-native-imlib#24]
重大BUG！！！安卓7以上缺少依赖包文件，导致APP闪退
![image](https://user-images.githubusercontent.com/16029204/59625177-364c2980-916b-11e9-8200-6fc128db9339.png)
我这边 安卓环境的：targetSdkVersion = 28

在这几个目录添加，libsqlite.so文件
参考：https://blog.csdn.net/java04/article/details/54617151

**Comment by qiuxiang** [comment]
目前的 SDK 确实会有这个问题，正在考虑把 libsqlite.so 集成进来

**Comment by luyixin** [comment]
老哥，赶紧哈，我等着用，谢谢

**Comment by luyixin** [comment]
目前主流的安卓手机的安卓版本大部分在6.0~9.0之间哈，感谢老哥了，我等着用哈，不然每次在android上改了，yarn装一次依赖包，又给重置了，很头疼
