### ISSUE TITLE
React-Native 中addReceiveMessageListener 监听不到消息

### ISSUE THREAD

**Issue by wanggang385** [rongcloud/rongcloud-react-native-imlib#27]
componentDidMount() {
            this.listener=addReceiveMessageListener(message => {
                const { content } = message.message;
                if (content.data && content.data.length > 999) {
                    content.data = content.data.substr(0, 100) + "...";
                }
                console.log("监听的消息:" + JSON.stringify(message));
            });
      
    }

进入页面时可以监听到⏫发送的消息，进入页面后，再发送消息，无法监听到

**Comment by qiuxiang** [comment]
不知道你说的进入页面时和进入页面后具体是指什么

**Comment by qiuxiang** [comment]
你说的页面是什么页面？做了什么操作？

**Comment by wanggang385** [comment]
进入聊天室页面，发送消息到聊天室，消息发送成功，监听不到发送的消息

**Comment by wanggang385** [comment]
![image](https://user-images.githubusercontent.com/51811665/60261395-58ce0780-990e-11e9-984d-707079a650cc.png)

**Comment by wanggang385** [comment]
看图上图，正常是不是发一条就监听到一条呢？

**Comment by qiuxiang** [comment]
意思是同一个页面里监听聊天室信息，同时也发送聊天信息，但发送的聊天信息没有被监听到？

**Comment by wanggang385** [comment]
是的

**Comment by wanggang385** [comment]
你用你们官网的Dome试试一下  我加入聊天室，发送消息，监听聊天室消息  该怎么做？

**Comment by qiuxiang** [comment]
我确认下

**Comment by wanggang385** [comment]
您好！怎么样？在急等您的回复！！！

**Comment by qiuxiang** [comment]
我试了，确实没有收到，可能 SDK 就是设计成不会收到自己的消息，要再用其他帐号来发送消息来测试

**Comment by wanggang385** [comment]
那个这个设计是不是不太合理呀  别人发是可以监听到

**Comment by lvpengrc** [comment]
你是接收消息的监听中，无法收到自己在聊天室中发送的消息吧
