### ISSUE TITLE
RN SDK 收到 通知类和自定义消息类型的 消息数据不正确

### ISSUE THREAD

**Issue by feshfans** [rongcloud/rongcloud-react-native-imlib#28]
应用服务端发送系统通知类消息，RN SDK 可以收到消息，但数据不对。如下图1， content 中只有 objectName, 而实际数据没有，而 web 端则没有问题，如图2。
![image](https://user-images.githubusercontent.com/19229145/60420695-ea918980-9c1a-11e9-87ee-533e154bb199.png)

![image](https://user-images.githubusercontent.com/19229145/60420657-d3eb3280-9c1a-11e9-9e04-a401fb975db9.png)

**Comment by qiuxiang** [comment]
暂时不支持自定义消息，SDK 的自定义消息是需要自己写原生代码实现的，目前还没找到能通过 js 端实现自定义消息的方法

**Comment by feshfans** [comment]
那融云内置的通知类消息呢？据我们的测试，通知类消息 RN SDK 也是上述这样的情况

**Comment by qiuxiang** [comment]
objectName 是什么？如果是内置的话，可能是漏掉了

**Comment by feshfans** [comment]
RC:CmdNtf , 应用服务端使用的 CmdNtfMessage 类， objectName 没有漏掉，因为 Java Server SDK 不填写 objectName 会报错，所以肯定是填写了的

**Comment by feshfans** [comment]
我看 rongcloud-react-native-imlib/lib/android/src/main/java/cn/rongcloud/imlib/react/Convert.java 类中 static WritableMap toJSON(String objectName, MessageContent content)  这个函数只处理了 6 种消息类型，而没有处理 RC:CmdNtf  消息类型

**Comment by qiuxiang** [comment]
晚点加上

**Comment by feshfans** [comment]
尽量快点哈，我们等着用哩，谢谢！

**Comment by qiuxiang** [comment]
已经完善了 android 的通知类消息，ios 稍后补上

**Comment by feshfans** [comment]
好的，谢谢。我们 ios 也在用 -_-

**Comment by feshfans** [comment]
你好，ios 今天可以修复完成么

**Comment by qiuxiang** [comment]
得明天才行，macbook 不在

**Comment by feshfans** [comment]
你好，ios 可以了么

**Comment by qiuxiang** [comment]
好了，发布新版本了
