### ISSUE TITLE
【BUG】消息阅读回执监听函数无效

### ISSUE THREAD

**Issue by luyixin** [rongcloud/rongcloud-react-native-imlib#29]
addReadReceiptReceivedListener 监听消息阅读回执无效
![image](https://user-images.githubusercontent.com/16029204/60456786-d1b1c400-9c6c-11e9-9074-58e45e11f416.png)

![image](https://user-images.githubusercontent.com/16029204/60456544-1557fe00-9c6c-11e9-847e-f669ac2932c2.png)
![image](https://user-images.githubusercontent.com/16029204/60456579-2e60af00-9c6c-11e9-9e08-62cd2ce704c5.png)
![image](https://user-images.githubusercontent.com/16029204/60456638-59e39980-9c6c-11e9-93b1-534a55fce215.png)
执行了发送消息阅读回执，消息阅读回执接受事件（addReadReceiptReceivedListener）不触发

rongcloud-react-native-imlib 版本: 0.2.3

**Comment by qiuxiang** [comment]
我确认下

**Comment by luyixin** [comment]
好的哈，辛苦了

**Comment by gengqizhi** [comment]
sendReadReceiptMessage 方法是取消未读数的吧? 调用后未读数一直不变啊

**Comment by webxiaohe** [comment]
Has the problem been solved

**Comment by qiuxiang** [comment]
<img src="https://user-images.githubusercontent.com/1709072/75981511-98c69f00-5f1f-11ea-9bc7-f0b7e6bb5e2d.png" width=360>

测试并没有问题，请参考 https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/example/examples/read-receipt.js
