### ISSUE TITLE
RN版本会加自定义消息类型吗?

### ISSUE THREAD

**Issue by gengqizhi** [rongcloud/rongcloud-react-native-imlib#30]
项目需要自定义消息, 原生有自定义消息, 但现在RN库不支持自定义消息, 以后会加上吗?

**Comment by qiuxiang** [comment]
目前是没有找到比较可行的方式实现自定义消息，如果有了好的方案是会加上的

**Comment by gengqizhi** [comment]
原生的文档上可以实现自定义消息,RN上应该也可以,唯一就定好类型, 消息体我们自己解析

**Comment by qiuxiang** [comment]
主要问题在于，不能从 js 端定义，只能写原生来定义

**Comment by gengqizhi** [comment]
觉得原生定义了就可以, 没必要让RN再次定义,就是写死, 如果我们需要多个自定义, 我们项目有很多类型的自定义消息, 我们是在自定义消息体的内容里的JSON数据里,加上type区分,自定义消息加上离线推送的内容就可以了.这样不能满足之前的逻辑吗?

**Comment by qiuxiang** [comment]
你的意思是固定定义一种消息？但提供一个字段给开发者自己填数据？如果是这样的话那并不是真正意义上的自定义消息，和用已有消息类型的 extra 字段进行扩展没什么区别。

原生 SDK 的自定义消息无法实现是因为，提供自定义消息的方法是在编译时确定的，但是 RN 却要运行时定义自定义消息。

**Comment by gengqizhi** [comment]
哦哦 那我用 extra 字段可以实现自定义消息, 那就不需要定义真正意义上的自定义消息, 之前没注意这个extra,我看一下能不能满足我们需要

**Comment by gengqizhi** [comment]
extra 字段可以满足项目的功能.谢谢!
