### ISSUE TITLE
获取会话列表时,getConversationList返回数据里没有是不是开启免打扰, 这个字段能加上吗?

### ISSUE THREAD

**Issue by gengqizhi** [rongcloud/rongcloud-react-native-imlib#35]
![image](https://user-images.githubusercontent.com/22095600/60794410-4b314100-a19c-11e9-937d-65b159b4a03a.png)

如果不加上这个免打扰的字段, 不能在会话列表页显示已开启免打扰.每个会话查询一次,效率太低.能给列表数据里加上吗?

**Comment by qiuxiang** [comment]
我看接口 android 是有这个字段的，ios 没有，我问问 sdk 那边

**Comment by gengqizhi** [comment]
在工单上说, 会话列表就是没有这个字段, 我们可以存服务器, 节省时间帮忙看一下,ios语音问题怎么样, 我在另一个问题里有说:https://github.com/rongcloud/rongcloud-react-native-imlib/issues/12#issuecomment-508893575
