### ISSUE TITLE
获取置顶时,没有获取单人的置顶状态. getTopConversationList,android没有方法

### ISSUE THREAD

**Issue by gengqizhi** [rongcloud/rongcloud-react-native-imlib#36]
获取置顶时,没有获取单人的置顶状态. getTopConversationList,android没有此方法
![WechatIMG4](https://user-images.githubusercontent.com/22095600/60880139-9a977000-a275-11e9-97ce-64f56848803c.jpeg)

**Comment by qiuxiang** [comment]
我看了接口 android 是没有 getTopConversationList 这个方法的
