### ISSUE TITLE
rn 官方的sdk 不能跑起来

### ISSUE THREAD

**Issue by 531290683** [rongcloud/rongcloud-react-native-imlib#37]
![e587d81743efea9886a072939d80a89](https://user-images.githubusercontent.com/49904977/60951131-1273a200-a32b-11e9-80cb-834b5d1e1de2.png)

**Comment by qiuxiang** [comment]
yarn build

**Comment by 531290683** [comment]
![image](https://user-images.githubusercontent.com/49904977/61019334-64203900-a3cc-11e9-93c7-c75eb45ab25f.png)
然后报了一个这个

**Comment by 531290683** [comment]
> 成纱

然后报一个这个https://github.com/rongcloud/rongcloud-react-native-imlib/issues/37#issuecomment-510296451

**Comment by 531290683** [comment]
> 成纱

![image](https://user-images.githubusercontent.com/49904977/61019475-e9a3e900-a3cc-11e9-8403-c74f45894cf4.png)
然后报了一个这个

**Comment by qiuxiang** [comment]
看 readme https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/README.md#%E8%BF%90%E8%A1%8C%E7%A4%BA%E4%BE%8B

**Comment by 531290683** [comment]
> 看自述[https：/github.com/rongCloud/rongCloud-本机-imlib/blob/master/README.md#%、E8%、BF%、90%、E8%、A1%、8C%、E7%、A4%、BA%、E4%、Be%8B](https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/README.md#%E8%BF%90%E8%A1%8C%E7%A4%BA%E4%BE%8B)

![image](https://user-images.githubusercontent.com/49904977/61035718-410c7e00-a3fa-11e9-8b15-0757a8834448.png)
rang然后真机上报了这个

**Comment by qiuxiang** [comment]
看起来是没有把库编译进去

**Comment by 531290683** [comment]
> 看起来是没有把库编译进去

加一个微信细说吧
18230780504

**Comment by 531290683** [comment]
> 看起来是没有把库编译进去

![image](https://user-images.githubusercontent.com/49904977/61107361-50e79900-a4b2-11e9-9471-b410eff55cee.png)
这个是怎么回事

**Comment by qiuxiang** [comment]
这个和一开始的是一样的

**Comment by 531290683** [comment]
> 这个和一开始的是一样的

![image](https://user-images.githubusercontent.com/49904977/61116109-6797eb00-a4c6-11e9-89f7-3e68415cee64.png)
我们跑到这里，这个问题是不是接口的问题，还是其他的

**Comment by qiuxiang** [comment]
这起来是本地配置的问题

**Comment by qiuxiang** [comment]
就截图的信息看，是 babel

**Comment by 531290683** [comment]
> 就截图的信息看，是 babel

![image](https://user-images.githubusercontent.com/49904977/61130378-1d743100-a4e9-11e9-8e2e-dfb377d2400c.png)
我加了这个生命周期函数调用官方的方法然后报了这个错
![image](https://user-images.githubusercontent.com/49904977/61130567-8065c800-a4e9-11e9-83a2-f8d4eee8c9d9.png)

**Comment by qiuxiang** [comment]
你截图的代码不是出错的地方

**Comment by 531290683** [comment]
> 你截图的代码不是出错的地方
![image](https://user-images.githubusercontent.com/49904977/61168736-35998e00-a585-11e9-8abe-ae35081e9073.png)
![image](https://user-images.githubusercontent.com/49904977/61168743-477b3100-a585-11e9-954b-7900e627ae0b.png)

报错提示里面有句话是无效变量
而我们代码里没有 ‘Cannot have a non-function arg after a function arg’ 这一段，这一段应该rn即时通讯项目下的js模块生成里的一句，应该在你方服务器代码中。最近rn官方版本更新后符号可能需要改变一下某些标点，请你检查一下，比如引号是否不全导致系统将返回语句理解变量而导致报错，谢谢。

**Comment by qiuxiang** [comment]
上面分析扯远了。。不过好歹给了一些有用的信息，本来我还以为是语法错误。

![image](https://user-images.githubusercontent.com/1709072/61169796-00486c80-a594-11e9-86c6-9e6c79ff4370.png)

你不能这么把第一个参数注释掉，这导致传给原生的参数就完全不对了。

**Comment by 531290683** [comment]
> 上面分析扯远了。。不过好歹给了一些有用的信息，本来我还以为是语法错误。
> 
> ![image](https://user-images.githubusercontent.com/1709072/61169796-00486c80-a594-11e9-86c6-9e6c79ff4370.png)
> 
> 你不能这么把第一个参数注释掉，这导致传给原生的参数就完全不对了。

![image](https://user-images.githubusercontent.com/49904977/61169964-8e712280-a595-11e9-954d-c26394aba05d.png)
但是放出来就会出现这个错误，我就试着注释了看看能行不

**Comment by qiuxiang** [comment]
这是你 token 这个变量没有赋值呀 = =
