### ISSUE TITLE
我应该如何获取会话列表呢？

### ISSUE THREAD

**Issue by cnpmge** [rongcloud/rongcloud-react-native-imlib#38]
![QQ截图20190808173501](https://user-images.githubusercontent.com/48587696/62692230-de130480-ba02-11e9-92ae-b067f07f8d2c.png)

**Comment by qiuxiang** [comment]
https://qiuxiang.github.io/react-native-rongcloud-imlib/api/globals.html#getconversationlist

**Comment by cnpmge** [comment]
我调用了这个函数，并成功返回了数据，但是用户的昵称以及头像信息并没有传递回来，看你们的官网教程是说用自己项目的服务器本地获得这些数据，但是这样是不是就多操作了一步，利用函数获取了数据，再根据获取的数据去后台拿到用户的头像与昵称？
