### ISSUE TITLE
一进行连接就直接报错

### ISSUE THREAD

**Issue by chinavane** [rongcloud/rongcloud-react-native-imlib#4]
![image](https://user-images.githubusercontent.com/8588836/57187704-af7a1f00-6f25-11e9-8f08-45af5ddb51f5.png)

**Comment by qiuxiang** [comment]
看一下 logcat

**Comment by chinavane** [comment]
bash-3.2# react-native log-android
info Starting the logger (/Users/v/Library/Android/sdk/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V)...
--------- beginning of system
--------- beginning of main
05-05 14:22:39.134  4816  4816 D ReactNative: ReactInstanceManager.ctor()
05-05 14:22:39.180  4816  4816 D ReactNative: ReactInstanceManager.createReactContextInBackground()
05-05 14:22:39.180  4816  4816 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-05 14:22:58.072  4906  4906 D ReactNative: ReactInstanceManager.ctor()
05-05 14:22:58.105  4906  4906 D ReactNative: ReactInstanceManager.createReactContextInBackground()
05-05 14:22:58.106  4906  4906 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-05 14:23:24.455  5146  5146 D ReactNative: ReactInstanceManager.ctor()
05-05 14:23:24.526  5146  5146 D ReactNative: ReactInstanceManager.createReactContextInBackground()
05-05 14:23:24.526  5146  5146 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-05 14:25:10.023  5385  5385 D ReactNative: ReactInstanceManager.ctor()
05-05 14:25:10.065  5385  5385 D ReactNative: ReactInstanceManager.createReactContextInBackground()
05-05 14:25:10.065  5385  5385 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
05-05 14:25:13.059  5385  5385 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
05-05 14:25:13.060  5385  5385 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-05 14:25:13.060  5385  5385 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-05 14:25:13.081  5385  5417 D ReactNative: ReactInstanceManager.createReactContext()
05-05 14:25:13.147  5385  5417 D ReactNative: Initializing React Xplat Bridge.
05-05 14:25:13.149  5385  5417 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-05 14:25:13.153  5385  5417 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-05 14:25:13.153  5385  5417 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-05 14:25:13.154  5385  5421 D ReactNative: ReactInstanceManager.setupReactContext()
05-05 14:25:13.155  5385  5421 D ReactNative: CatalystInstanceImpl.initialize()
05-05 14:25:13.159  5385  5421 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-05 14:25:13.614  5385  5420 I ReactNativeJS: Running application "rongRNTest" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
05-05 14:25:19.855  5385  5385 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
05-05 14:25:19.856  5385  5385 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-05 14:25:19.856  5385  5385 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-05 14:25:19.856  5385  5385 D ReactNative: ReactInstanceManager.tearDownReactContext()
05-05 14:25:19.858  5385  5385 D ReactNative: CatalystInstanceImpl.destroy() start
05-05 14:25:19.859  5385  5432 D ReactNative: ReactInstanceManager.createReactContext()
05-05 14:25:19.875  5385  5432 D ReactNative: Initializing React Xplat Bridge.
05-05 14:25:19.877  5385  5432 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-05 14:25:19.879  5385  5432 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-05 14:25:19.880  5385  5432 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-05 14:25:19.880  5385  5434 D ReactNative: ReactInstanceManager.setupReactContext()
05-05 14:25:19.881  5385  5434 D ReactNative: CatalystInstanceImpl.initialize()
05-05 14:25:19.884  5385  5434 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-05 14:25:19.998  5385  5419 D ReactNative: CatalystInstanceImpl.destroy() end
05-05 14:25:20.252  5385  5433 I ReactNativeJS: Running application "rongRNTest" with appParams: {"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
05-05 14:25:28.598  5385  5385 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
05-05 14:25:28.599  5385  5385 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-05 14:25:28.599  5385  5385 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-05 14:25:28.599  5385  5385 D ReactNative: ReactInstanceManager.tearDownReactContext()
05-05 14:25:28.601  5385  5385 D ReactNative: CatalystInstanceImpl.destroy() start
05-05 14:25:28.603  5385  5439 D ReactNative: ReactInstanceManager.createReactContext()
05-05 14:25:28.614  5385  5439 D ReactNative: Initializing React Xplat Bridge.
05-05 14:25:28.617  5385  5439 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-05 14:25:28.623  5385  5439 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-05 14:25:28.623  5385  5439 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-05 14:25:28.623  5385  5441 D ReactNative: ReactInstanceManager.setupReactContext()
05-05 14:25:28.624  5385  5441 D ReactNative: CatalystInstanceImpl.initialize()
05-05 14:25:28.625  5385  5441 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-05 14:25:28.783  5385  5406 D ReactNative: CatalystInstanceImpl.destroy() end
05-05 14:25:29.051  5385  5440 I ReactNativeJS: Running application "rongRNTest" with appParams: {"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
05-05 14:26:16.522  5385  5385 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
05-05 14:26:16.522  5385  5385 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
05-05 14:26:16.522  5385  5385 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
05-05 14:26:16.522  5385  5385 D ReactNative: ReactInstanceManager.tearDownReactContext()
05-05 14:26:16.524  5385  5385 D ReactNative: CatalystInstanceImpl.destroy() start
05-05 14:26:16.525  5385  5454 D ReactNative: ReactInstanceManager.createReactContext()
05-05 14:26:16.540  5385  5454 D ReactNative: Initializing React Xplat Bridge.
05-05 14:26:16.541  5385  5454 D ReactNative: Initializing React Xplat Bridge before initializeBridge
05-05 14:26:16.547  5385  5454 D ReactNative: Initializing React Xplat Bridge after initializeBridge
05-05 14:26:16.547  5385  5454 D ReactNative: CatalystInstanceImpl.runJSBundle()
05-05 14:26:16.548  5385  5459 D ReactNative: ReactInstanceManager.setupReactContext()
05-05 14:26:16.548  5385  5459 D ReactNative: CatalystInstanceImpl.initialize()
05-05 14:26:16.551  5385  5459 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
05-05 14:26:16.656  5385  5456 D ReactNative: CatalystInstanceImpl.destroy() end
05-05 14:26:16.947  5385  5458 I ReactNativeJS: Running application "rongRNTest" with appParams: {"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
--------- beginning of crash

**Comment by chinavane** [comment]
![Snipaste_2019-05-05_14-31-24](https://user-images.githubusercontent.com/8588836/57189586-00e4d700-6f43-11e9-9e5f-c6106f32e951.png)
![Snipaste_2019-05-05_14-31-54](https://user-images.githubusercontent.com/8588836/57189587-017d6d80-6f43-11e9-907c-062a2b762476.png)

![Snipaste_2019-05-05_14-33-31](https://user-images.githubusercontent.com/8588836/57189591-03473100-6f43-11e9-84ca-2fc912299e34.png)

**Comment by qiuxiang** [comment]
你得用 android studio 看，log-android 把一些信息过滤掉了

**Comment by yunwuxin** [comment]
我也有这个问题  

错误日志是这个 

![image](https://user-images.githubusercontent.com/2168125/57210105-ff341580-700d-11e9-9a6b-1bba1551686f.png)

**Comment by qiuxiang** [comment]
这个情况忘了说明了，Android SDK 依赖 libsqlite，在 API 23 之前可以用系统的 libsalite，如果是 API > 23 就不行，但可以在项目里引入 libsqlite。

最简单的做法是将 target API 设置成 23：
https://github.com/rongcloud/rongcloud-react-native-imlib/blob/48c05b11bfc90e00073a52f95e9d95e465dfcb85/android/build.gradle#L8

**Comment by qiuxiang** [comment]
最新版本已经集成 libsqlite
