### ISSUE TITLE
如何支持react-native 0.60以上版本

### ISSUE THREAD

**Issue by EMNEIL** [rongcloud/rongcloud-react-native-imlib#49]
react-native 0.60 以上版本 用react-native link 导入，运行报"React/RCTEventEmitter.h"这个文件不存在，路径有问题

**Comment by viking2016** [comment]
同求啊，试了各种方法都不成功

**Comment by viking2016** [comment]
> react-native 0.60 以上版本 用react-native link 导入，运行报"React/RCTEventEmitter.h"这个文件不存在，路径有问题

老哥，问题解决了吗，能否指点一下
