### ISSUE TITLE
发送消息 一直是失败 -3  

### ISSUE THREAD

**Issue by yunwuxin** [rongcloud/rongcloud-react-native-imlib#5]
在我自己的app里  或者 用你们的demo  都是这样

**Comment by yunwuxin** [comment]
找到原因了  这两个地方需要使用hasKey判断下  直接获取在没有传这个数据的时候会出错

https://github.com/rongcloud/rongcloud-react-native-imlib/blob/48c05b11bfc90e00073a52f95e9d95e465dfcb85/lib/android/src/main/java/cn/rongcloud/imlib/react/RCIMClientModule.java#L428

https://github.com/rongcloud/rongcloud-react-native-imlib/blob/48c05b11bfc90e00073a52f95e9d95e465dfcb85/lib/android/src/main/java/cn/rongcloud/imlib/react/RCIMClientModule.java#L435

**Comment by qiuxiang** [comment]
这里确实没处理好

**Comment by yunwuxin** [comment]
@qiuxiang 修正一下？

**Comment by qiuxiang** [comment]
不对，`ReadableMap userInfoMap = map.getMap("userInfo"); ` 如果不存在对应的 key 不应该出错，而是会返回 null 才对，不然 example 也会出错的，我先确定是不是会出问题。

**Comment by qiuxiang** [comment]
发了修正版本
