### ISSUE TITLE
Android searchConversations 传值错误

### ISSUE THREAD

**Issue by superhos** [rongcloud/rongcloud-react-native-imlib#52]
````java
    @ReactMethod
    public void searchConversations(String keyword, ReadableArray types, ReadableArray objectNames, final Promise promise) {
        ConversationType[] conversationTypes = toConversationTypeArray(types);
        String[] objectNamesArray = toStringArray(types);
       ....
````

RCIMClientModule中的searchConversations方法， `String[] objectNamesArray = toStringArray(types);`该行把types传进去了，应该传objectNames。

目前会报类型错误，影响较大，建议尽快修改更新谢谢！，

**Comment by superhos** [comment]
本地修改后发现searchConversations无法得到正确结果，这个方法验证不通过

**Comment by qiuxiang** [comment]
错误信息截图出来看下

**Comment by superhos** [comment]
> 错误信息截图出来看下

这两个问题直接Review代码就可以看到了吧。
第一个问题是类型错误，因为把types当做objectNames传过去了。
第二个问题是没有把map push到result里面，promise返回的是一个空的result。

**Comment by qiuxiang** [comment]
好的 ，明白了，大概中午的时候修复

**Comment by superhos** [comment]
> 好的 ，明白了，大概中午的时候修复

好的，谢谢哈!
