### ISSUE TITLE
如何运行起来本项目的 iOS 示例

### ISSUE THREAD

**Issue by hiscc** [rongcloud/rongcloud-react-native-imlib#53]
我是直接下载本项目到本地然后按照 README.md 下的运行示例来操作的
1. 先去 https://www.rongcloud.cn/downloads 下载了 iOS IMLib SDK 
2. yarn global add typescript
3. yarn build   
4. yarn 「自己加的」
5. yarn run-ios

结果
<img width="640" alt="未命名" src="https://user-images.githubusercontent.com/17979372/64579717-6bf15f00-d3b6-11e9-8ee2-c4f9f27c28bd.png">

### 所以我又按照文档去运行本项目下的 iOS 示例应用
<img width="640" alt="融云demo" src="https://user-images.githubusercontent.com/17979372/64579764-904d3b80-d3b6-11e9-8861-d69323c91c09.png">
<img width="640"  alt="融云demo-1" src="https://user-images.githubusercontent.com/17979372/64579766-93e0c280-d3b6-11e9-98f3-ea89cd247048.png">

**Comment by qiuxiang** [comment]
项目更新到了 RN 0.60+，ios 转为 cocoapod，参考最新文档
