### ISSUE TITLE
发送的图片信息，接受不到

### ISSUE THREAD

**Issue by Time-coding** [rongcloud/rongcloud-react-native-imlib#55]
"react": "16.8.6",
 "react-native": "0.60.5",
"rongcloud-react-native-imlib": "^0.3.9"

issue：
Android获取不到会话列表
发送到的图片接受不到

**Comment by qiuxiang** [comment]
用了哪几个接口？

**Comment by Time-coding** [comment]
发送图片的和语音的接口，直接就是发送成功，没有获取到上传进度，
`
import { sendMediaMessage, cancelSendMediaMessage, ObjectName } from "rongcloud-react-native-imlib";

const content = { objectName: ObjectName.Image, local: "file:///image_path" };
const callback = {
  success(messageId) {
    console.log("发送成功：" + messageId);
  },
  progress(progress, messageId) {
    console.log(`发送进度: ${progress} %`);

    // 消息发送过程中可随时取消发送
    cancelSendMediaMessage(messageId);
  },
  cancel() {
    console.log("发送取消");
  },
  error(errorCode) {
    console.log("发送失败：" + errorCode);
  }
};

sendMediaMessage({ conversationType, targetId, content }, callback);
`

**Comment by Time-coding** [comment]
https://docs.rongcloud.cn/im/imlib/rn/message/send-message/
按这个文档发送的，图片和语音发送过去，local就是null

**Comment by qiuxiang** [comment]
建议参考下示例：https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/example/examples/send-message.js

**Comment by Time-coding** [comment]
发送语音消息，如果是ObjectName：RC:VcMsg 是用sendMessage,如果用RC:HQVCMsg 就用sendMediaMessage是吧

**Comment by Time-coding** [comment]
我按照这个文档https://docs.rongcloud.cn/im/imlib/rn/message/send-message/发送语音消息，androd可以相互发送语音，但是ios和android交互就不行

**Comment by Time-coding** [comment]
我先把这个消息关掉，图片可以获取到，但是语音数据，ios还是收不到
