### ISSUE TITLE
insertIncomingMessage方法 IOS不兼容

### ISSUE THREAD

**Issue by superhos** [rongcloud/rongcloud-react-native-imlib#57]
**复现流程**
通过 insertIncomingMessage 来对未存在的聊天对象添加一条消息，Android可正常增加会话和显示消息，IOS无会话新增

**代码**
````javascript
await insertIncomingMessage(ConversationType.PRIVATE, '0000-00000-0000-0000', myID, 10, message.content, +new Date())
````

**Comment by superhos** [comment]
使用SDK版本：0.3.6
react版本：16.2.0
react-native: 0.52.2

**Comment by qiuxiang** [comment]
我尝试在 [example](https://github.com/rongcloud/rongcloud-react-native-imlib/blob/master/example/examples/insert-message.js) 上修改，并没有出现问题。

![image](https://user-images.githubusercontent.com/1709072/69963121-7f8e0b00-154a-11ea-8e48-1ad5ea114375.png)

<img width=320 src="https://user-images.githubusercontent.com/1709072/69962949-14dccf80-154a-11ea-877f-ae165bf47499.png">

<img width=320 src="https://user-images.githubusercontent.com/1709072/69963023-42297d80-154a-11ea-82c0-8e123b179633.png">

**Comment by qiuxiang** [comment]
另外提一下，你的代码里 `insertIncomingMessage` 最后一个参数是无效的

**Comment by superhos** [comment]
好的 感谢测试，我这边持续debug一下看看是什么引起的。
