### ISSUE TITLE
imlib是不是没集成推送的方法？？？

### ISSUE THREAD

**Issue by chujian** [rongcloud/rongcloud-react-native-imlib#67]
- [ ]
![1587800310848](https://user-images.githubusercontent.com/10389215/80274166-023a8100-870b-11ea-9d22-b608eead2ea7.jpg)
![1587800335732](https://user-images.githubusercontent.com/10389215/80274168-04044480-870b-11ea-9267-0d5764253f5a.jpg)

import {
  addPushArrivedListener,
  setPushContentShowStatus,
  getPushContentShowStatus
} from "rongcloud-react-native-imlib";

这几个都提示没这个方法

**Comment by chujian** [comment]
项目的demo也提示这个错误，

**Comment by qiuxiang** [comment]
iOS 还是 Android？demo 出错的是哪个功能？

**Comment by chujian** [comment]
今天得到工单回复了，说不支持IOS，就是DEMO的最后一个功能，查询什么推送状态。没事了
