### ISSUE TITLE
集成成功后，收到消息但是没有推送

### ISSUE THREAD

**Issue by a805883237** [rongcloud/rongcloud-react-native-imlib#69]
react-native 环境如下：
```
react: 17.0.2 => 17.0.2
react-native: ~0.64.2 => 0.64.2
```

集成 当前包版本如下：
```
"rongcloud-react-native-imlib": "^0.3.13",
```

集成后 `connect` 、 `addReceiveMessageListener` 函数均可正常执行，并且 `addReceiveMessageListener` 也可正常触发 (信息正常)

唯一问题就是没有通知横幅，使用 安卓模拟器、安卓真机（android8.0）、IOS真机，均没有收到推送

在[融云开发者文档-推送](https://docs.rongcloud.cn/v4/5X/views/rtc/call/noui/push/android.html#) 中找到这样的代码
```
PushConfig config = new PushConfig.Builder()
        .build();
RongPushClient.setPushConfig(config);
```

但是在 `com/myApp/MainApplication.java` 的 `onCreate` 方法内使用时，无法导入 `PushConfig` 和 `RongPushClient` 类。

尝试通过 以下代码引用时，`RongPushClient` 和 `PushConfig` 报红。
```
import io.rong.push.RongPushClient; // 文件路径应该是没有问题，但是无法引用，不知为何，非安卓开发，不甚了解
import io.rong.push.pushconfig.PushConfig;
```

所以请问正确的引用方式是什么，或者有没有 `react-native: 0.64` 版本的使用文档？

望回复，万分感谢。

**Comment by gdmec07140512** [comment]
+1

**Comment by a805883237** [comment]
问过官方，官方给出的回复是不支持消息推送的，需要开发者自行适配。

鄙人能力有限，暂时放弃此业务
