### ISSUE TITLE
有已经集成好的界面吗？就是一套sdk，我直接拿来用就好了

### ISSUE THREAD

**Issue by mumu19920210** [rongcloud/rongcloud-react-native-imlib#8]

**Comment by qiuxiang** [comment]
还没有，这个库只是 imlib

**Comment by mumu19920210** [comment]
好吧，那还要自己写界面

**Comment by mumu19920210** [comment]
那比如：表情、语音、视频这些呢？

**Comment by qiuxiang** [comment]
表情需要自己实现，语音、视频支持发送接收，不支持实时音视频

**Comment by mumu19920210** [comment]
好吧。那谢谢了，不支持实时的话，就先不用这个库拉，谢谢你

**Comment by vpjacob** [comment]
表情需要自己实现，语音、视频支持发送接收，不支持实时音视频

语音，视频，不支持实时是什么意思，不能收到推送吗

**Comment by qiuxiang** [comment]
实时音视频的是指类似于微信的视频、语音通话，不是不能实时接收的意思。

**Comment by linhanyang** [comment]
会考虑实现一套seal talk类似的解决方案吗？

**Comment by lvpengrc** [comment]
你好，RN 只提供 Lib 接口，UI 的实现还需要自行实现
